# -*- coding: utf-8 -*-
"""animalesCrud.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D5q6gldbMSNeyL8x1BwxBihukU-Nhx9C
"""

class Animal:
    def __init__(self, nombre, especie):
        self.nombre = nombre
        self.especie = especie

    def __str__(self):
        return f"{self.nombre} ({self.especie})"


def mostrar_animal(animales):
    if animales:
        print("Aniamles ingresadas:")
        for animales in animales:
            print(animales)
    else:
        print("No se han ingresado Animales.")


def eliminar_animal(animales):
    if animales:
        nombre = input("Ingrese el nombre del animal a eliminar: ")
        animales_filtrados = [animal for animal in animales if animal.nombre != nombre]
        if len(animales_filtrados) < len(animales):
            animales[:] = animales_filtrados
            print("Animal eliminado exitosamente.")
        else:
            print("No se encontró el animal con ese nombre.")
    else:
        print("No se han ingresadoel animal.")



def modificar_animal(animales):
    if animales:
        nombre = input("Ingrese el nombre de la película a modificar: ")
        for animal in animales:
            if animal.nombre == nombre:
                nuevo_nombre = input("Ingrese el nuevo nombre del animal: ")
                nuevo_especie = int(input("Ingrese el nuevo año del animal: "))
                animal.nombre = nuevo_nombre
                animal.especie = nuevo_especie
                print("Animal modificada exitosamente.")
                return
        print("No se encontró el animal con ese nombre.")
    else:
        print("No se han ingresado animales.")

def menu():
    animales = []

    while True:
        print("------ MENÚ ------")
        print("1. Ingresar animal")
        print("2. Mostrar animal")
        print("3. Eliminar animal")
        print("4. Modificar animal")
        print("0. Salir")

        opcion = input("Ingrese una opción: ")

        if opcion == "1":
            nombre = input("Ingrese el nombre del animal: ")
            especie = input("Ingrese la especie del animal: ")
            animal = Animal(nombre, especie)
            animales.append(animal)
            print("Animal ingresado exitosamente.")
        elif opcion == "2":
            mostrar_animal(animales)
        elif opcion == "3":
            eliminar_animal(animales)
        elif opcion == "4":
            modificar_animal(animales)
        elif opcion == "0":
            print("¡Hasta luego!")
            break
        else:
            print("Opción inválida. Por favor, ingrese una opción válida.")


menu()