# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XZKS8llTJry_s5rXI24ovpNxOxP7hJxz
"""

class Celular:
    def __init__(self, marca, modelo):
        self.marca = marca
        self.modelo = modelo

    def __str__(self):
        return f"{self.marca} ({self.modelo})"


def mostrar_celulares(celulares):
    if celulares:
        print("Celulares ingresados:")
        for celular in celulares:
            print(celular)
    else:
        print("No se han ingresado celulares.")


def eliminar_celular(celulares):
    if celulares:
        marca = input("Ingrese la marca del celular a eliminar: ")
        celulares_filtrados = [celular for celular in celulares if celular.marca != marca] # list Comprehensions
        if len(celulares_filtrados) < len(celulares):
            celulares[:] = celulares_filtrados
            print("Celular eliminado exitosamente.")
        else:
            print("No se encontró un celular con esa marca.")
    else:
        print("No se han ingresado celulares.")



def modificar_celular(celulares):
    if celulares:
        marca = input("Ingrese marca del celular a modificar: ")
        for celular in celulares:
            if celular.marca == marca:
                nueva_marca = input("Ingrese el nuevo nombre de la película: ")
                nuevo_modelo = int(input("Ingrese el nuevo año de la película: "))
                celular.marca = nueva_marca
                celular.modelo = nuevo_modelo
                print("celular modificado exitosamente.")
                return
        print("No se encontró un celular con esa marca.")
    else:
        print("No se han ingresado celulares.")

def menu():
    celulares = []

    while True:
        print("------ MENÚ ------")
        print("1. Ingresar celular")
        print("2. Mostrar celulares")
        print("3. Eliminar celular")
        print("4. Modificar celular")
        print("0. Salir")

        opcion = input("Ingrese una opción: ")

        if opcion == "1":
            marca = input("Ingrese la marca del celular: ")
            modelo = input("Ingrese el modelo: ")
            celular = Celular(marca, modelo)
            celulares.append(celular)
            print("Celular ingresado exitosamente.")
        elif opcion == "2":
            mostrar_celulares(celulares)
        elif opcion == "3":
            eliminar_celular(celulares)
        elif opcion == "4":
            modificar_celular(celulares)
        elif opcion == "0":
            print("¡Hasta luego!")
            break
        else:
            print("Opción inválida. Por favor, ingrese una opción válida.")


menu()